package utils;

import java.io.FileWriter;
import java.io.IOException;
import java.util.Set;

/**
 * Генератор HTML отчетов о покрытии UI
 */
public class CoverageReportGenerator {

    public static void generateHTMLReport(Set<String> allElements, Set<String> coveredElements, String filePath) {
        try (FileWriter writer = new FileWriter(filePath)) {
            double coveragePercent = allElements.isEmpty() ? 0 : (double) coveredElements.size() / allElements.size() * 100;

            writer.write("<!DOCTYPE html>\n");
            writer.write("<html lang='en'>\n");
            writer.write("<head>\n");
            writer.write("    <meta charset='UTF-8'>\n");
            writer.write("    <title>UI Coverage Report</title>\n");
            writer.write("    <style>\n");
            writer.write("        body { font-family: Arial, sans-serif; margin: 20px; line-height: 1.6; }\n");
            writer.write("        .summary { background: #f5f5f5; padding: 20px; border-radius: 8px; margin-bottom: 20px; }\n");
            writer.write("        .coverage-bar { background: #e0e0e0; height: 25px; border-radius: 12px; margin: 15px 0; overflow: hidden; }\n");
            writer.write("        .coverage-fill { background: #4CAF50; height: 100%; transition: width 0.5s; }\n");
            writer.write("        .element-list { margin: 20px 0; }\n");
            writer.write("        .covered { color: #4CAF50; padding: 4px 8px; margin: 2px 0; background: #f8fff8; border-left: 3px solid #4CAF50; }\n");
            writer.write("        .uncovered { color: #f44336; padding: 4px 8px; margin: 2px 0; background: #fff8f8; border-left: 3px solid #f44336; }\n");
            writer.write("        .stats { display: flex; gap: 20px; margin: 10px 0; }\n");
            writer.write("        .stat-box { padding: 10px; background: white; border-radius: 5px; flex: 1; text-align: center; }\n");
            writer.write("    </style>\n");
            writer.write("</head>\n");
            writer.write("<body>\n");

            // Заголовок и суммарная статистика
            writer.write("    <h1>🎯 UI Coverage Report</h1>\n");
            writer.write("    <div class='summary'>\n");
            writer.write("        <h2>📊 Summary</h2>\n");
            writer.write("        <div class='stats'>\n");
            writer.write("            <div class='stat-box'><h3>" + allElements.size() + "</h3><p>Total Elements</p></div>\n");
            writer.write("            <div class='stat-box'><h3 style='color: #4CAF50'>" + coveredElements.size() + "</h3><p>Covered Elements</p></div>\n");
            writer.write("            <div class='stat-box'><h3 style='color: #f44336'>" + (allElements.size() - coveredElements.size()) + "</h3><p>Uncovered Elements</p></div>\n");
            writer.write("            <div class='stat-box'><h3>" + String.format("%.1f", coveragePercent) + "%</h3><p>Coverage</p></div>\n");
            writer.write("        </div>\n");
            writer.write("        <div class='coverage-bar'>\n");
            writer.write("            <div class='coverage-fill' style='width: " + coveragePercent + "%'></div>\n");
            writer.write("        </div>\n");
            writer.write("    </div>\n");

            // Список покрытых элементов
            writer.write("    <div class='element-list'>\n");
            writer.write("        <h2>✅ Covered Elements (" + coveredElements.size() + ")</h2>\n");
            if (coveredElements.isEmpty()) {
                writer.write("        <p>No elements covered yet</p>\n");
            } else {
                for (String element : coveredElements) {
                    writer.write("        <div class='covered'>✓ " + escapeHtml(element) + "</div>\n");
                }
            }
            writer.write("    </div>\n");

            // Список непокрытых элементов
            writer.write("    <div class='element-list'>\n");
            writer.write("        <h2>❌ Uncovered Elements (" + (allElements.size() - coveredElements.size()) + ")</h2>\n");
            if (allElements.size() == coveredElements.size()) {
                writer.write("        <p>🎉 All elements are covered!</p>\n");
            } else {
                for (String element : allElements) {
                    if (!coveredElements.contains(element)) {
                        writer.write("        <div class='uncovered'>✗ " + escapeHtml(element) + "</div>\n");
                    }
                }
            }
            writer.write("    </div>\n");

            writer.write("    <footer style='margin-top: 40px; padding: 20px; text-align: center; color: #666;'>\n");
            writer.write("        Generated by UI Coverage Tracker\n");
            writer.write("    </footer>\n");
            writer.write("</body>\n");
            writer.write("</html>\n");

            System.out.println("📄 HTML report generated: " + filePath);

        } catch (IOException e) {
            System.err.println("❌ Error generating HTML report: " + e.getMessage());
        }
    }

    private static String escapeHtml(String text) {
        if (text == null) return "";
        return text.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }
}